--------------------------------------------------------
--  File created - Thursday-February-25-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "<USERNAME>"."DEPARTMENT" 
   (	"DNUM" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"MANAGER" VARCHAR2(10 BYTE), 
	"STARTDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPENDENT
--------------------------------------------------------

  CREATE TABLE "<USERNAME>"."DEPENDENT" 
   (	"NINUM" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"SEX" VARCHAR2(1 BYTE), 
	"RELATIONSHIP" VARCHAR2(50 BYTE), 
	"BIRTHDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "<USERNAME>"."EMPLOYEE" 
   (	"NINUM" VARCHAR2(10 BYTE), 
	"FNAME" VARCHAR2(50 BYTE), 
	"LNAME" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"SEX" VARCHAR2(1 BYTE), 
	"BIRTHDATE" TIMESTAMP (6), 
	"SALARY" NUMBER, 
	"SUPERVISOR" VARCHAR2(10 BYTE), 
	"DNUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOCATION
--------------------------------------------------------

  CREATE TABLE "<USERNAME>"."LOCATION" 
   (	"DNUM" NUMBER, 
	"CITY" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROJECT
--------------------------------------------------------

  CREATE TABLE "<USERNAME>"."PROJECT" 
   (	"PNUM" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(50 BYTE), 
	"DNUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WORKSON
--------------------------------------------------------

  CREATE TABLE "<USERNAME>"."WORKSON" 
   (	"NINUM" VARCHAR2(10 BYTE), 
	"PNUM" NUMBER, 
	"HOURS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into <USERNAME>.DEPARTMENT
SET DEFINE OFF;
Insert into <USERNAME>.DEPARTMENT (DNUM,NAME,MANAGER,STARTDATE) values (1,'Finance','CD567435C',to_date('14-APR-16','DD-MON-RR'));
Insert into <USERNAME>.DEPARTMENT (DNUM,NAME,MANAGER,STARTDATE) values (2,'IT','FH758329O',to_date('14-APR-16','DD-MON-RR'));
Insert into <USERNAME>.DEPARTMENT (DNUM,NAME,MANAGER,STARTDATE) values (3,'Sales','TY574892A',to_date('14-APR-16','DD-MON-RR'));
Insert into <USERNAME>.DEPARTMENT (DNUM,NAME,MANAGER,STARTDATE) values (4,'Marketing','HT564892B',to_date('14-APR-16','DD-MON-RR'));
Insert into <USERNAME>.DEPARTMENT (DNUM,NAME,MANAGER,STARTDATE) values (5,'Research & Development','TH869203G',to_date('14-APR-16','DD-MON-RR'));
REM INSERTING into <USERNAME>.DEPENDENT
SET DEFINE OFF;
Insert into <USERNAME>.DEPENDENT (NINUM,NAME,SEX,RELATIONSHIP,BIRTHDATE) values ('GD457691D','Samantha','F','Daughter',to_timestamp('25-MAY-16 13.28.48.033000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into <USERNAME>.DEPENDENT (NINUM,NAME,SEX,RELATIONSHIP,BIRTHDATE) values ('GT583572F','Ross','M','Son',to_timestamp('23-NOV-16 13.29.29.226000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into <USERNAME>.DEPENDENT (NINUM,NAME,SEX,RELATIONSHIP,BIRTHDATE) values ('GT583572F','Thomas','M','Son',to_timestamp('23-NOV-16 13.29.29.226000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into <USERNAME>.DEPENDENT (NINUM,NAME,SEX,RELATIONSHIP,BIRTHDATE) values ('FH758329O','Frances','F','Grand-daughter',to_timestamp('09-FEB-16 14.01.36.351000000','DD-MON-RR HH24.MI.SSXFF'));
REM INSERTING into <USERNAME>.EMPLOYEE
SET DEFINE OFF;
Insert into <USERNAME>.EMPLOYEE (NINUM,FNAME,LNAME,ADDRESS,SEX,BIRTHDATE,SALARY,SUPERVISOR,DNUM) values ('AB765876A','Andrew','Jones','31 Apple Way','M',to_timestamp('16-FEB-16 12.04.33.304000000','DD-MON-RR HH24.MI.SSXFF'),35000,'CD567435C',1);
Insert into <USERNAME>.EMPLOYEE (NINUM,FNAME,LNAME,ADDRESS,SEX,BIRTHDATE,SALARY,SUPERVISOR,DNUM) values ('CD567435C','Barbara','Lang','43 Cedar Croft','F',to_timestamp('18-MAY-16 12.05.41.821000000','DD-MON-RR HH24.MI.SSXFF'),65000,null,1);
Insert into <USERNAME>.EMPLOYEE (NINUM,FNAME,LNAME,ADDRESS,SEX,BIRTHDATE,SALARY,SUPERVISOR,DNUM) values ('GD457691D','Christopher','Lee','7 Abbot Road','M',to_timestamp('20-FEB-16 12.06.42.870000000','DD-MON-RR HH24.MI.SSXFF'),18000,'FH758329O',2);
Insert into <USERNAME>.EMPLOYEE (NINUM,FNAME,LNAME,ADDRESS,SEX,BIRTHDATE,SALARY,SUPERVISOR,DNUM) values ('FG865729B','Dani','Blair','6 Clement Road','F',to_timestamp('16-MAR-16 12.08.44.853000000','DD-MON-RR HH24.MI.SSXFF'),28000,'FH758329O',3);
Insert into <USERNAME>.EMPLOYEE (NINUM,FNAME,LNAME,ADDRESS,SEX,BIRTHDATE,SALARY,SUPERVISOR,DNUM) values ('GT583572F','Eduardo','Vargas','57 Elm Row','M',to_timestamp('15-SEP-16 12.12.14.727000000','DD-MON-RR HH24.MI.SSXFF'),56000,'FH758329O',2);
Insert into <USERNAME>.EMPLOYEE (NINUM,FNAME,LNAME,ADDRESS,SEX,BIRTHDATE,SALARY,SUPERVISOR,DNUM) values ('FH758329O','Frances','Whyte','9 Berry View','F',to_timestamp('25-AUG-16 12.13.52.258000000','DD-MON-RR HH24.MI.SSXFF'),62000,'CD567435C',2);
Insert into <USERNAME>.EMPLOYEE (NINUM,FNAME,LNAME,ADDRESS,SEX,BIRTHDATE,SALARY,SUPERVISOR,DNUM) values ('HT564892B','Graham','Browne','46 Montague Street','M',to_timestamp('19-JAN-16 12.15.19.850000000','DD-MON-RR HH24.MI.SSXFF'),24000,'CD567435C',4);
Insert into <USERNAME>.EMPLOYEE (NINUM,FNAME,LNAME,ADDRESS,SEX,BIRTHDATE,SALARY,SUPERVISOR,DNUM) values ('TY574892A','Harry','Smith','3 Rosy Drive','M',to_timestamp('18-MAY-16 12.16.34.475000000','DD-MON-RR HH24.MI.SSXFF'),45000,'CD567435C',3);
Insert into <USERNAME>.EMPLOYEE (NINUM,FNAME,LNAME,ADDRESS,SEX,BIRTHDATE,SALARY,SUPERVISOR,DNUM) values ('FG584572D','Iain','Munroe','46 Dew Place','M',to_timestamp('28-MAY-16 13.13.12.221000000','DD-MON-RR HH24.MI.SSXFF'),23000,'HT564892B',4);
Insert into <USERNAME>.EMPLOYEE (NINUM,FNAME,LNAME,ADDRESS,SEX,BIRTHDATE,SALARY,SUPERVISOR,DNUM) values ('TH869203G','Jackie','Walker','5 Sloane Street','F',to_timestamp('29-DEC-16 13.14.41.021000000','DD-MON-RR HH24.MI.SSXFF'),40000,'CD567435C',5);
Insert into <USERNAME>.EMPLOYEE (NINUM,FNAME,LNAME,ADDRESS,SEX,BIRTHDATE,SALARY,SUPERVISOR,DNUM) values ('YH564384R','Kelly','Locke','48 Glassford Terrace','F',to_timestamp('29-APR-16 13.46.11.725000000','DD-MON-RR HH24.MI.SSXFF'),36000,'TH869203G',5);
Insert into <USERNAME>.EMPLOYEE (NINUM,FNAME,LNAME,ADDRESS,SEX,BIRTHDATE,SALARY,SUPERVISOR,DNUM) values ('TY586838F','Laura','James','5 Target Drive','F',to_timestamp('07-APR-16 13.47.10.292000000','DD-MON-RR HH24.MI.SSXFF'),36000,'TH869203G',5);
Insert into <USERNAME>.EMPLOYEE (NINUM,FNAME,LNAME,ADDRESS,SEX,BIRTHDATE,SALARY,SUPERVISOR,DNUM) values ('YH563728F','Michael','Anderson','90 Darnley Road','M',to_timestamp('18-NOV-16 13.48.16.023000000','DD-MON-RR HH24.MI.SSXFF'),18000,'TY586838F',5);
REM INSERTING into <USERNAME>.LOCATION
SET DEFINE OFF;
Insert into <USERNAME>.LOCATION (DNUM,CITY) values (1,'Glasgow');
Insert into <USERNAME>.LOCATION (DNUM,CITY) values (2,'Glasgow');
Insert into <USERNAME>.LOCATION (DNUM,CITY) values (3,'Glasgow');
Insert into <USERNAME>.LOCATION (DNUM,CITY) values (4,'Glasgow');
Insert into <USERNAME>.LOCATION (DNUM,CITY) values (5,'Aberdeen');
REM INSERTING into <USERNAME>.PROJECT
SET DEFINE OFF;
Insert into <USERNAME>.PROJECT (PNUM,NAME,CITY,DNUM) values (101,'Financial Reporting','Glasgow',1);
Insert into <USERNAME>.PROJECT (PNUM,NAME,CITY,DNUM) values (102,'Server Migration','Edinburgh',2);
Insert into <USERNAME>.PROJECT (PNUM,NAME,CITY,DNUM) values (103,'Budget Review','Glasgow',1);
Insert into <USERNAME>.PROJECT (PNUM,NAME,CITY,DNUM) values (104,'Product Launch','Edinburgh',3);
Insert into <USERNAME>.PROJECT (PNUM,NAME,CITY,DNUM) values (105,'Database Upgrade','Glasgow',2);
Insert into <USERNAME>.PROJECT (PNUM,NAME,CITY,DNUM) values (106,'Launch Facebook Page','Glasgow',4);
Insert into <USERNAME>.PROJECT (PNUM,NAME,CITY,DNUM) values (107,'Virtual Reality','Edinburgh',5);
Insert into <USERNAME>.PROJECT (PNUM,NAME,CITY,DNUM) values (108,'Neural Networks','Aberdeen',5);
REM INSERTING into <USERNAME>.WORKSON
SET DEFINE OFF;
Insert into <USERNAME>.WORKSON (NINUM,PNUM,HOURS) values ('CD567435C',101,25);
Insert into <USERNAME>.WORKSON (NINUM,PNUM,HOURS) values ('CD567435C',103,15);
Insert into <USERNAME>.WORKSON (NINUM,PNUM,HOURS) values ('AB765876A',101,40);
Insert into <USERNAME>.WORKSON (NINUM,PNUM,HOURS) values ('FG865729B',104,35);
Insert into <USERNAME>.WORKSON (NINUM,PNUM,HOURS) values ('TY574892A',104,35);
Insert into <USERNAME>.WORKSON (NINUM,PNUM,HOURS) values ('TY574892A',106,5);
Insert into <USERNAME>.WORKSON (NINUM,PNUM,HOURS) values ('GT583572F',102,30);
Insert into <USERNAME>.WORKSON (NINUM,PNUM,HOURS) values ('GD457691D',102,30);
Insert into <USERNAME>.WORKSON (NINUM,PNUM,HOURS) values ('FH758329O',102,15);
Insert into <USERNAME>.WORKSON (NINUM,PNUM,HOURS) values ('TH869203G',107,35);
Insert into <USERNAME>.WORKSON (NINUM,PNUM,HOURS) values ('YH564384R',107,30);
Insert into <USERNAME>.WORKSON (NINUM,PNUM,HOURS) values ('TY586838F',108,15);
Insert into <USERNAME>.WORKSON (NINUM,PNUM,HOURS) values ('TY586838F',107,15);
Insert into <USERNAME>.WORKSON (NINUM,PNUM,HOURS) values ('YH563728F',108,35);
Insert into <USERNAME>.WORKSON (NINUM,PNUM,HOURS) values ('CD567435C',108,5);
Insert into <USERNAME>.WORKSON (NINUM,PNUM,HOURS) values ('FG865729B',108,10);
Insert into <USERNAME>.WORKSON (NINUM,PNUM,HOURS) values ('TY574892A',108,10);
--------------------------------------------------------
--  DDL for Index PROJECT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "<USERNAME>"."PROJECT_PK" ON "<USERNAME>"."PROJECT" ("PNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "<USERNAME>"."EMPLOYEE_PK" ON "<USERNAME>"."EMPLOYEE" ("NINUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEPT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "<USERNAME>"."DEPT_PK" ON "<USERNAME>"."DEPARTMENT" ("DNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index WORKSON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "<USERNAME>"."WORKSON_PK" ON "<USERNAME>"."WORKSON" ("NINUM", "PNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEPENDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "<USERNAME>"."DEPENDENT_PK" ON "<USERNAME>"."DEPENDENT" ("NINUM", "NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOCATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "<USERNAME>"."LOCATION_PK" ON "<USERNAME>"."LOCATION" ("DNUM", "CITY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "<USERNAME>"."DEPARTMENT" ADD CONSTRAINT "DEPT_PK" PRIMARY KEY ("DNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "<USERNAME>"."LOCATION" ADD CONSTRAINT "LOCATION_PK" PRIMARY KEY ("DNUM", "CITY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROJECT
--------------------------------------------------------

  ALTER TABLE "<USERNAME>"."PROJECT" ADD CONSTRAINT "PROJECT_PK" PRIMARY KEY ("PNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPENDENT
--------------------------------------------------------

  ALTER TABLE "<USERNAME>"."DEPENDENT" ADD CONSTRAINT "DEPENDENT_PK" PRIMARY KEY ("NINUM", "NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "<USERNAME>"."EMPLOYEE" MODIFY ("NINUM" NOT NULL ENABLE);
  ALTER TABLE "<USERNAME>"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("NINUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WORKSON
--------------------------------------------------------

  ALTER TABLE "<USERNAME>"."WORKSON" ADD CONSTRAINT "WORKSON_PK" PRIMARY KEY ("NINUM", "PNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
